((package-attr-short   . "bluos-controller")
 (package-attr-long    . "packages.x86_64-linux.bluos-controller")
 (package-name         . "bluos-controller")
 (package-type         . "executable")
 (package-target-short . "bluos-controller")
 (package-target-long  . "bin/bluos-controller")
 (run-attr-short       . "bluos-controller")
 (run-attr-long        . "packages.x86_64-linux.bluos-controller")
 ;; run-name must be the same as run-target-short
 ;; run-type must be "executable"
 (run-target-short     . "bluos-controller")
 (run-target-long      . "bin/bluos-controller")
 (nix-latest           . "2.18")
 (nixos-latest         . "23.05")
 (platforms            . "Linux on x86-64 machines"))
