name: "CI"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: shajra
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: cat ~/.config/nix/nix.conf
    - run: nix --print-build-logs build
    - run: nix path-info
